/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "CControl.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_getreleasedversionccontroldatareceiver_8 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (getreleasedversionccontroldatareceiver_8_svc(result, rqstp));
}

int
_detstates_8 (detstates_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (detstates_8_svc(argp->values, argp->seqNr, result, rqstp));
}

int
_actualsignalindications_8 (actualsignalindications_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (actualsignalindications_8_svc(argp->values, argp->seqNr, result, rqstp));
}

int
_actualstatus_8 (actualstatus_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (actualstatus_8_svc(argp->values, argp->seqNr, result, rqstp));
}

int
_requestedstatus_8 (requestedstatus_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (requestedstatus_8_svc(argp->rs, argp->seqNr, result, rqstp));
}

int
_targetstage_8 (targetstage_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (targetstage_8_svc(argp->ts, argp->devTick, argp->seqNr, result, rqstp));
}

int
_intersectionrides_8 (intersectionrides_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (intersectionrides_8_svc(argp->rides, argp->seqNr, result, rqstp));
}

int
_devicevalues_8 (devicevalues_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (devicevalues_8_svc(argp->values, argp->seqNr, result, rqstp));
}

int
_rideevent_8 (rideevent_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rideevent_8_svc(argp->r09, argp->seqNr, result, rqstp));
}

int
_reportallqueuesareidle_8 (reportallqueuesareidle_8_argument *argp, void *result, struct svc_req *rqstp)
{
	return (reportallqueuesareidle_8_svc(argp->isReportRequested, argp->seqNr, result, rqstp));
}

int
_checkconfig_8 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (checkconfig_8_svc(*argp, result, rqstp));
}

int
_activate_8 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (activate_8_svc(*argp, result, rqstp));
}

int
_cleanupconfigcheck_8 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cleanupconfigcheck_8_svc(result, rqstp));
}

int
_archiveinsertevent_8 (enum ArchiveSelectorCctrl  *argp, void *result, struct svc_req *rqstp)
{
	return (archiveinsertevent_8_svc(*argp, result, rqstp));
}

int
_subscribedevicevariables_8 (OitdCctrlA  *argp, void *result, struct svc_req *rqstp)
{
	return (subscribedevicevariables_8_svc(*argp, result, rqstp));
}

int
_unsubscribedevicevariables_8 (OitdCctrlA  *argp, void *result, struct svc_req *rqstp)
{
	return (unsubscribedevicevariables_8_svc(*argp, result, rqstp));
}

int
_getdevicevaluesmetadata_8 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (getdevicevaluesmetadata_8_svc(result, rqstp));
}

int
_getnlsdefinitions_8 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (getnlsdefinitions_8_svc(result, rqstp));
}

void
ccontroldatareceiver_8(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		detstates_8_argument detstates_8_arg;
		actualsignalindications_8_argument actualsignalindications_8_arg;
		actualstatus_8_argument actualstatus_8_arg;
		requestedstatus_8_argument requestedstatus_8_arg;
		targetstage_8_argument targetstage_8_arg;
		intersectionrides_8_argument intersectionrides_8_arg;
		devicevalues_8_argument devicevalues_8_arg;
		rideevent_8_argument rideevent_8_arg;
		reportallqueuesareidle_8_argument reportallqueuesareidle_8_arg;
		int checkconfig_8_arg;
		int activate_8_arg;
		enum ArchiveSelectorCctrl archiveinsertevent_8_arg;
		OitdCctrlA subscribedevicevariables_8_arg;
		OitdCctrlA unsubscribedevicevariables_8_arg;
	} argument;
	union {
		int getreleasedversionccontroldatareceiver_8_res;
		CheckRespondCctrl checkconfig_8_res;
		enum RetCodeCctrl subscribedevicevariables_8_res;
		enum RetCodeCctrl unsubscribedevicevariables_8_res;
		DeviceValuesMetaDataCctrl getdevicevaluesmetadata_8_res;
		NlsMappingsCctrl getnlsdefinitions_8_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case getReleasedVersionCcontrolDataReceiver:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_getreleasedversionccontroldatareceiver_8;
		break;

	case detStates:
		_xdr_argument = (xdrproc_t) xdr_detstates_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_detstates_8;
		break;

	case actualSignalIndications:
		_xdr_argument = (xdrproc_t) xdr_actualsignalindications_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_actualsignalindications_8;
		break;

	case actualStatus:
		_xdr_argument = (xdrproc_t) xdr_actualstatus_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_actualstatus_8;
		break;

	case requestedStatus:
		_xdr_argument = (xdrproc_t) xdr_requestedstatus_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_requestedstatus_8;
		break;

	case targetStage:
		_xdr_argument = (xdrproc_t) xdr_targetstage_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_targetstage_8;
		break;

	case intersectionRides:
		_xdr_argument = (xdrproc_t) xdr_intersectionrides_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_intersectionrides_8;
		break;

	case deviceValues:
		_xdr_argument = (xdrproc_t) xdr_devicevalues_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_devicevalues_8;
		break;

	case rideEvent:
		_xdr_argument = (xdrproc_t) xdr_rideevent_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rideevent_8;
		break;

	case reportAllQueuesAreIdle:
		_xdr_argument = (xdrproc_t) xdr_reportallqueuesareidle_8_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_reportallqueuesareidle_8;
		break;

	case checkConfig:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_CheckRespondCctrl;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_checkconfig_8;
		break;

	case activate:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_activate_8;
		break;

	case cleanupConfigCheck:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cleanupconfigcheck_8;
		break;

	case archiveInsertEvent:
		_xdr_argument = (xdrproc_t) xdr_ArchiveSelectorCctrl;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_archiveinsertevent_8;
		break;

	case subscribeDeviceVariables:
		_xdr_argument = (xdrproc_t) xdr_OitdCctrlA;
		_xdr_result = (xdrproc_t) xdr_RetCodeCctrl;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_subscribedevicevariables_8;
		break;

	case unSubscribeDeviceVariables:
		_xdr_argument = (xdrproc_t) xdr_OitdCctrlA;
		_xdr_result = (xdrproc_t) xdr_RetCodeCctrl;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unsubscribedevicevariables_8;
		break;

	case getDeviceValuesMetaData:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_DeviceValuesMetaDataCctrl;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_getdevicevaluesmetadata_8;
		break;

	case getNlsDefinitions:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_NlsMappingsCctrl;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_getnlsdefinitions_8;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!ccontroldatareceiver_8_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
