/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "CControl.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
getreleasedversionccontroldatareceiver_8(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getReleasedVersionCcontrolDataReceiver, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
detstates_8(DetRawValuesExchg values, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	detstates_8_argument arg;
	arg.values = values;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, detStates, (xdrproc_t) xdr_detstates_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
actualsignalindications_8(SignalIndicationsCctrl values, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	actualsignalindications_8_argument arg;
	arg.values = values;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, actualSignalIndications, (xdrproc_t) xdr_actualsignalindications_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
actualstatus_8(ActualStatusCctrl values, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	actualstatus_8_argument arg;
	arg.values = values;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, actualStatus, (xdrproc_t) xdr_actualstatus_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
requestedstatus_8(RequestedStatusCctrl rs, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	requestedstatus_8_argument arg;
	arg.rs = rs;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, requestedStatus, (xdrproc_t) xdr_requestedstatus_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
targetstage_8(TargetStagePtr ts, quad_t devTick, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	targetstage_8_argument arg;
	arg.ts = ts;
	arg.devTick = devTick;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, targetStage, (xdrproc_t) xdr_targetstage_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
intersectionrides_8(IntersectionRidesCctrl rides, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	intersectionrides_8_argument arg;
	arg.rides = rides;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, intersectionRides, (xdrproc_t) xdr_intersectionrides_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
devicevalues_8(DeviceValuesCctrl values, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	devicevalues_8_argument arg;
	arg.values = values;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, deviceValues, (xdrproc_t) xdr_devicevalues_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rideevent_8(RideEventCctrl r09, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	rideevent_8_argument arg;
	arg.r09 = r09;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, rideEvent, (xdrproc_t) xdr_rideevent_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
reportallqueuesareidle_8(bool_t isReportRequested, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	reportallqueuesareidle_8_argument arg;
	arg.isReportRequested = isReportRequested;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, reportAllQueuesAreIdle, (xdrproc_t) xdr_reportallqueuesareidle_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
checkconfig_8(int configTypes, CheckRespondCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, checkConfig,
		(xdrproc_t) xdr_int, (caddr_t) &configTypes,
		(xdrproc_t) xdr_CheckRespondCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
activate_8(int sysJobId, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, activate,
		(xdrproc_t) xdr_int, (caddr_t) &sysJobId,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cleanupconfigcheck_8(void *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, cleanupConfigCheck, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
archiveinsertevent_8(enum ArchiveSelectorCctrl selector, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, archiveInsertEvent,
		(xdrproc_t) xdr_ArchiveSelectorCctrl, (caddr_t) &selector,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
subscribedevicevariables_8(OitdCctrlA oitds, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, subscribeDeviceVariables,
		(xdrproc_t) xdr_OitdCctrlA, (caddr_t) &oitds,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unsubscribedevicevariables_8(OitdCctrlA oitds, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, unSubscribeDeviceVariables,
		(xdrproc_t) xdr_OitdCctrlA, (caddr_t) &oitds,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getdevicevaluesmetadata_8(DeviceValuesMetaDataCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getDeviceValuesMetaData, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_DeviceValuesMetaDataCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getnlsdefinitions_8(NlsMappingsCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getNlsDefinitions, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_NlsMappingsCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getreleasedversionccontrolservice_8(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getReleasedVersionCcontrolService, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
subscribe4tdt_8(char *inetadr, int port, TdtSubscriptionInfoCctrl si, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	subscribe4tdt_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.si = si;
	return (clnt_call (clnt, subscribe4Tdt, (xdrproc_t) xdr_subscribe4tdt_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unsubscribe4tdt_8(char *inetadr, int port, enum MkjtricDataTypeCctrl tdt, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	unsubscribe4tdt_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.tdt = tdt;
	return (clnt_call (clnt, unsubscribe4Tdt, (xdrproc_t) xdr_unsubscribe4tdt_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
allqueuesareidle_8(char *inetadr, int port, int seqNr, void *clnt_res,  CLIENT *clnt)
{
	allqueuesareidle_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.seqNr = seqNr;
	return (clnt_call (clnt, allQueuesAreIdle, (xdrproc_t) xdr_allqueuesareidle_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
renew_8(char *inetadr, int port, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	renew_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	return (clnt_call (clnt, renew, (xdrproc_t) xdr_renew_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
adddesiredsgswitchingevents_8(ExternalSgSwitchingEventArray sgSwitchingEvents, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, addDesiredSgSwitchingEvents,
		(xdrproc_t) xdr_ExternalSgSwitchingEventArray, (caddr_t) &sgSwitchingEvents,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
adddesiredstageswitchingevents_8(ExternalStageSwitchingEventArray stageSwitchingEvents, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, addDesiredStageSwitchingEvents,
		(xdrproc_t) xdr_ExternalStageSwitchingEventArray, (caddr_t) &stageSwitchingEvents,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getearliesttime4stagetransition_8(quad_t notBeforeTime, int toStage, quad_t *clnt_res,  CLIENT *clnt)
{
	getearliesttime4stagetransition_8_argument arg;
	arg.notBeforeTime = notBeforeTime;
	arg.toStage = toStage;
	return (clnt_call (clnt, getEarliestTime4StageTransition, (xdrproc_t) xdr_getearliesttime4stagetransition_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_quad_t, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
checkadddesiredstageswitchingevents_8(ExternalStageSwitchingEventArray stageSwitchingEvents, int allowedTypesOfViolation, bool_t *clnt_res,  CLIENT *clnt)
{
	checkadddesiredstageswitchingevents_8_argument arg;
	arg.stageSwitchingEvents = stageSwitchingEvents;
	arg.allowedTypesOfViolation = allowedTypesOfViolation;
	return (clnt_call (clnt, checkAddDesiredStageSwitchingEvents, (xdrproc_t) xdr_checkadddesiredstageswitchingevents_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_bool, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setintersectionstate_8(enum RequestedStatusPriorityCctrl priority, enum RequestedMainNodeStateCctrl value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setintersectionstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setIntersectionState, (xdrproc_t) xdr_setintersectionstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setsubintersectionstate_8(enum RequestedStatusPriorityCctrl priority, enum RequestedNodeStateCctrl value, int sysJobId, int key, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setsubintersectionstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.key = key;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setSubIntersectionState, (xdrproc_t) xdr_setsubintersectionstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setsignalprogram_8(enum RequestedStatusPriorityCctrl priority, int value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setsignalprogram_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setSignalProgram, (xdrproc_t) xdr_setsignalprogram_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setspecialintervention_8(enum RequestedStatusPriorityCctrl priority, int value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setspecialintervention_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setSpecialIntervention, (xdrproc_t) xdr_setspecialintervention_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setmodvastate_8(enum RequestedStatusPriorityCctrl priority, RequestedModificationStateCctrl value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setmodvastate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setModVAState, (xdrproc_t) xdr_setmodvastate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setmodivstate_8(enum RequestedStatusPriorityCctrl priority, RequestedModificationStateCctrl value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setmodivstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setModIVState, (xdrproc_t) xdr_setmodivstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setmodoevstate_8(enum RequestedStatusPriorityCctrl priority, RequestedModificationStateCctrl value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setmodoevstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setModOEVState, (xdrproc_t) xdr_setmodoevstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setsynchronizationstate_8(enum RequestedStatusPriorityCctrl priority, RequestedModificationStateCctrl value, int sysJobId, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setsynchronizationstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setSynchronizationState, (xdrproc_t) xdr_setsynchronizationstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setprojectspecificmodstate_8(enum RequestedStatusPriorityCctrl priority, RequestedModificationStateCctrl value, int sysJobId, int key, quad_t durationInMs, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setprojectspecificmodstate_8_argument arg;
	arg.priority = priority;
	arg.value = value;
	arg.sysJobId = sysJobId;
	arg.key = key;
	arg.durationInMs = durationInMs;
	return (clnt_call (clnt, setProjectspecificModState, (xdrproc_t) xdr_setprojectspecificmodstate_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
droppriority_8(enum RequestedStatusPriorityCctrl priority, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, dropPriority,
		(xdrproc_t) xdr_RequestedStatusPriorityCctrl, (caddr_t) &priority,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
clearall_8(void *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, clearAll, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
settaactualstatus_8(char *host, int port, TTVModOnOffStateCctrlA taStates, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	settaactualstatus_8_argument arg;
	arg.host = host;
	arg.port = port;
	arg.taStates = taStates;
	return (clnt_call (clnt, setTaActualStatus, (xdrproc_t) xdr_settaactualstatus_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getcomponentparams_8(char *componentName, MkjtricActuationComponentParamsResult *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getComponentParams,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &componentName,
		(xdrproc_t) xdr_MkjtricActuationComponentParamsResult, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getdraftcomponentparams_8(char *componentName, char *inetadr, int port, MkjtricActuationComponentParamsResult *clnt_res,  CLIENT *clnt)
{
	getdraftcomponentparams_8_argument arg;
	arg.componentName = componentName;
	arg.inetadr = inetadr;
	arg.port = port;
	return (clnt_call (clnt, getDraftComponentParams, (xdrproc_t) xdr_getdraftcomponentparams_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_MkjtricActuationComponentParamsResult, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setcltstatus_8(char *host, int port, CltStatusMsgsCctrl status, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setcltstatus_8_argument arg;
	arg.host = host;
	arg.port = port;
	arg.status = status;
	return (clnt_call (clnt, setCltStatus, (xdrproc_t) xdr_setcltstatus_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
archivegetoldest_8(enum ArchiveSelectorCctrl selector, ArchiveResultCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, archiveGetOldest,
		(xdrproc_t) xdr_ArchiveSelectorCctrl, (caddr_t) &selector,
		(xdrproc_t) xdr_ArchiveResultCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
archivegetyoungest_8(enum ArchiveSelectorCctrl selector, ArchiveResultCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, archiveGetYoungest,
		(xdrproc_t) xdr_ArchiveSelectorCctrl, (caddr_t) &selector,
		(xdrproc_t) xdr_ArchiveResultCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
archivegetlaterthan_8(enum ArchiveSelectorCctrl selector, quad_t primaryKey, quad_t start, int maxCount, ArchiveResultArrayCctrl *clnt_res,  CLIENT *clnt)
{
	archivegetlaterthan_8_argument arg;
	arg.selector = selector;
	arg.primaryKey = primaryKey;
	arg.start = start;
	arg.maxCount = maxCount;
	return (clnt_call (clnt, archiveGetLaterThan, (xdrproc_t) xdr_archivegetlaterthan_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ArchiveResultArrayCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
addmsgresetarchive_8(int sysJobId, MsgParameterCctrl archiveType, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	addmsgresetarchive_8_argument arg;
	arg.sysJobId = sysJobId;
	arg.archiveType = archiveType;
	return (clnt_call (clnt, addMsgResetArchive, (xdrproc_t) xdr_addmsgresetarchive_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getaggregationcycle_8(AggregationCycleResultCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getAggregationCycle, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_AggregationCycleResultCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
setaggregationcycle_8(int samplingInterval, int offset, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setaggregationcycle_8_argument arg;
	arg.samplingInterval = samplingInterval;
	arg.offset = offset;
	return (clnt_call (clnt, setAggregationCycle, (xdrproc_t) xdr_setaggregationcycle_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getaggregationsignalling_8(AggregationSignallingResultCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getAggregationSignalling, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_AggregationSignallingResultCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
setaggregationsignalling_8(int maxSamplingInterval, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, setAggregationSignalling,
		(xdrproc_t) xdr_int, (caddr_t) &maxSamplingInterval,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
forwardptrequest_8(int sysJobId, R09TelegramCctrl telegram, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	forwardptrequest_8_argument arg;
	arg.sysJobId = sysJobId;
	arg.telegram = telegram;
	return (clnt_call (clnt, forwardPtRequest, (xdrproc_t) xdr_forwardptrequest_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getintersectionversionasxmlstring_8(char **clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getIntersectionVersionAsXmlString, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getsystemconfigversionasxmlstring_8(char **clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getSystemConfigVersionAsXmlString, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getdraftintersectionversionasxmlstring_8(char *inetadr, int port, char **clnt_res,  CLIENT *clnt)
{
	getdraftintersectionversionasxmlstring_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	return (clnt_call (clnt, getDraftIntersectionVersionAsXmlString, (xdrproc_t) xdr_getdraftintersectionversionasxmlstring_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getdraftsystemconfigversionasxmlstring_8(char *inetadr, int port, char **clnt_res,  CLIENT *clnt)
{
	getdraftsystemconfigversionasxmlstring_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	return (clnt_call (clnt, getDraftSystemConfigVersionAsXmlString, (xdrproc_t) xdr_getdraftsystemconfigversionasxmlstring_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getversions_8(VersionsCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getVersions, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_VersionsCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getcantonetconfig_8(CantoNetConfigCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getCantoNetConfig, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_CantoNetConfigCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getselectedcfg_8(enum CfgSelector arg1, SelectedConfig *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getSelectedCfg,
		(xdrproc_t) xdr_CfgSelector, (caddr_t) &arg1,
		(xdrproc_t) xdr_SelectedConfig, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getdraftselectedcfg_8(char *inetadr, int port, enum CfgSelector arg3, SelectedConfig *clnt_res,  CLIENT *clnt)
{
	getdraftselectedcfg_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.arg3 = arg3;
	return (clnt_call (clnt, getDraftSelectedCfg, (xdrproc_t) xdr_getdraftselectedcfg_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_SelectedConfig, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getselectedcfginfo_8(enum CfgInfoSelector selector, SelectedCfgInfo *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getSelectedCfgInfo,
		(xdrproc_t) xdr_CfgInfoSelector, (caddr_t) &selector,
		(xdrproc_t) xdr_SelectedCfgInfo, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getconfigdatainfoznr_8(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getConfigDataInfoZNr, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getconfigdatainfofnr_8(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getConfigDataInfoFNr, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
registerasconfigconsumer_8(char *inetadr, int port, int configTypeSet, enum UnitId uid, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	registerasconfigconsumer_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.configTypeSet = configTypeSet;
	arg.uid = uid;
	return (clnt_call (clnt, registerAsConfigConsumer, (xdrproc_t) xdr_registerasconfigconsumer_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregisterasconfigconsumer_8(char *inetadr, int port, int configTypeSet, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	unregisterasconfigconsumer_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.configTypeSet = configTypeSet;
	return (clnt_call (clnt, unregisterAsConfigConsumer, (xdrproc_t) xdr_unregisterasconfigconsumer_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
registerdevicevariableprovider_8(char *inetadr, int port, int tcpPort, char *dvpName, char *dvpVersion, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	registerdevicevariableprovider_8_argument arg;
	arg.inetadr = inetadr;
	arg.port = port;
	arg.tcpPort = tcpPort;
	arg.dvpName = dvpName;
	arg.dvpVersion = dvpVersion;
	return (clnt_call (clnt, registerDeviceVariableProvider, (xdrproc_t) xdr_registerdevicevariableprovider_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setdevicevalues_8(DeviceValuesCctrl dvs, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, setDeviceValues,
		(xdrproc_t) xdr_DeviceValuesCctrl, (caddr_t) &dvs,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
subscribe4devicevariables_8(OitdCctrlA oitds, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, subscribe4DeviceVariables,
		(xdrproc_t) xdr_OitdCctrlA, (caddr_t) &oitds,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unsubscribe4devicevariables_8(OitdCctrlA oitds, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, unSubscribe4DeviceVariables,
		(xdrproc_t) xdr_OitdCctrlA, (caddr_t) &oitds,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unsubscribealldevicevariables_8(enum RetCodeCctrl *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, unSubscribeAllDeviceVariables, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
checkifoitdexists_8(OitdCctrl oitd, bool_t *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, checkIfOitdExists,
		(xdrproc_t) xdr_OitdCctrl, (caddr_t) &oitd,
		(xdrproc_t) xdr_bool, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getdevicevaluesmetadatalist_8(DeviceValuesMetaDataCctrlA *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, getDeviceValuesMetaDataList, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_DeviceValuesMetaDataCctrlA, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
getdevicevaluesusedindex_8(DeviceValueIndexType dvit, DeviceValuesUsedIndicesCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getDeviceValuesUsedIndex,
		(xdrproc_t) xdr_DeviceValueIndexType, (caddr_t) &dvit,
		(xdrproc_t) xdr_DeviceValuesUsedIndicesCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
setsplcycletimecounterto_8(int signalProgramNumber, int newCycleTimeCounterValue, quad_t atTickTime, int durationMs, int priority, InitiatorCCtrl initiator, int sysJobId, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	setsplcycletimecounterto_8_argument arg;
	arg.signalProgramNumber = signalProgramNumber;
	arg.newCycleTimeCounterValue = newCycleTimeCounterValue;
	arg.atTickTime = atTickTime;
	arg.durationMs = durationMs;
	arg.priority = priority;
	arg.initiator = initiator;
	arg.sysJobId = sysJobId;
	return (clnt_call (clnt, setSplCycleTimeCounterTo, (xdrproc_t) xdr_setsplcycletimecounterto_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
stallsplcycletimecounterto_8(int signalProgramNumber, int newCycleTimeCounterValue, quad_t atTickTime, int durationMs, int priority, InitiatorCCtrl initiator, int sysJobId, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	stallsplcycletimecounterto_8_argument arg;
	arg.signalProgramNumber = signalProgramNumber;
	arg.newCycleTimeCounterValue = newCycleTimeCounterValue;
	arg.atTickTime = atTickTime;
	arg.durationMs = durationMs;
	arg.priority = priority;
	arg.initiator = initiator;
	arg.sysJobId = sysJobId;
	return (clnt_call (clnt, stallSplCycleTimeCounterTo, (xdrproc_t) xdr_stallsplcycletimecounterto_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
invalidatecycletimecounterat_8(int signalProgramNumber, quad_t atTickTime, int durationMs, int priority, InitiatorCCtrl initiator, int sysJobId, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	invalidatecycletimecounterat_8_argument arg;
	arg.signalProgramNumber = signalProgramNumber;
	arg.atTickTime = atTickTime;
	arg.durationMs = durationMs;
	arg.priority = priority;
	arg.initiator = initiator;
	arg.sysJobId = sysJobId;
	return (clnt_call (clnt, invalidateCycleTimeCounterAt, (xdrproc_t) xdr_invalidatecycletimecounterat_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
resetcyclemonitor_8(int partialIntersectionMask, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, resetCycleMonitor,
		(xdrproc_t) xdr_int, (caddr_t) &partialIntersectionMask,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getcycletimelinewithprioritylt_8(int priority, CycleTimelineCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getCycleTimelineWithPriorityLT,
		(xdrproc_t) xdr_int, (caddr_t) &priority,
		(xdrproc_t) xdr_CycleTimelineCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
resetfaultlock_8(void *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, resetFaultLock, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
prepare4shutdown2update_8(bool_t useEmergencyOpMode, int sysJobId, char **clnt_res,  CLIENT *clnt)
{
	prepare4shutdown2update_8_argument arg;
	arg.useEmergencyOpMode = useEmergencyOpMode;
	arg.sysJobId = sysJobId;
	return (clnt_call (clnt, prepare4Shutdown2Update, (xdrproc_t) xdr_prepare4shutdown2update_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
prepare4tashutdown2update_8(int sysJobId, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, prepare4TaShutdown2Update,
		(xdrproc_t) xdr_int, (caddr_t) &sysJobId,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
isfeaturelicensed_8(char *feature, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, isFeatureLicensed,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &feature,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
docontrolcenterif_8(enum ProcessControl startStopRestart, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, doControlCenterIf,
		(xdrproc_t) xdr_ProcessControl, (caddr_t) &startStopRestart,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
settalock_8(char *host, int port, TaLocksCctrl locks, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	settalock_8_argument arg;
	arg.host = host;
	arg.port = port;
	arg.locks = locks;
	return (clnt_call (clnt, setTaLock, (xdrproc_t) xdr_settalock_8_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
processedamli_8(AmliDtosCctrl amlis, enum RetCodeCctrl *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, processedAMLi,
		(xdrproc_t) xdr_AmliDtosCctrl, (caddr_t) &amlis,
		(xdrproc_t) xdr_RetCodeCctrl, (caddr_t) clnt_res,
		TIMEOUT));
}
